### ISSUE TITLE
依旧提示 systemctl: command not found

### ISSUE THREAD

**Issue by nobodysclown** [gcsong023/wrt1panel#1]
## 系统是iStoreOS

[1Panel Log]: ======================= 开始安装 ======================= 
设置 1Panel 安装目录（默认为/opt）：
[1Panel Log]: 您选择的安装路径为 /opt 
[1Panel Log]: 检测到 Docker 已安装，跳过安装步骤 
[1Panel Log]: 启动 Docker  
install.sh: line 65: systemctl: command not found
[1Panel Log]: 检测到 Docker Compose 已安装，跳过安装步骤 
设置 1Panel 端口（默认为22402）：8090
[1Panel Log]: 您设置的端口为：8090 
设置 1Panel 面板用户（默认为5fa10eeee6）：root
[1Panel Log]: 您设置的面板用户为：root 
设置 1Panel 面板密码（默认为de69630bb2）：
[1Panel Log]: 配置 1Panel Service 
cp: can't create '/etc/systemd/system': No such file or directory
install.sh: line 320: systemctl: command not found
install.sh: line 320: systemctl: command not found
[1Panel Log]: 启动 1Panel 服务 
install.sh: line 323: systemctl: command not found
[1Panel Log]: 1Panel 服务启动出错! 

## 卸载也有报错
root@iStoreOS:~# 1pctl uninstall
卸载将会完全清除 1Panel 服务和数据目录，是否继续 [y/n] : y
================== 开始卸载 1Panel Linux 服务器运维管理面板 ==================

1) 停止 1Panel 服务进程...
/usr/bin/1pctl: line 54: systemctl: command not found
2) 删除 1Panel 服务和数据目录...
3) 重新加载服务配置文件...
/usr/bin/1pctl: line 64: systemctl: command not found
/usr/bin/1pctl: line 65: systemctl: command not found

**Comment by gcsong023** [comment]
我猜测你使用的安装脚本是官方原版安装脚本。
如果你的WRT是X86_64平台的话，试试以下命令：
```sh
wget https://github.com/gcsong023/wrt1panel/releases/download/v1.10.9-lts/1panel-v1.10.9-lts-linux-amd64.tar.gz  && tar zxvf 1panel-v1.10.9-lts-linux-amd64.tar.gz && cd 1panel-v1.10.9-lts-linux-amd64 && bash install.sh   #示例 linux-amd64 平台
```
其他平台的话，请到release 下载相应平台的压缩包；也可以用以下一键安装命令安装官方编译1panel文件 ：
```sh
curl -sSL https://raw.githubusercontent.com/gcsong023/wrt_installer/wrt_1panel/quick_start.sh -o quick_start.sh && bash quick_start.sh
```

**Comment by gcsong023** [comment]
> ### 请描述您的问题
> ## 系统是iStoreOS
> [1Panel Log]: ======================= 开始安装 ======================= 设置 1Panel 安装目录（默认为/opt）： [1Panel Log]: 您选择的安装路径为 /opt [1Panel Log]: 检测到 Docker 已安装，跳过安装步骤 [1Panel Log]: 启动 Docker install.sh: line 65: systemctl: command not found [1Panel Log]: 检测到 Docker Compose 已安装，跳过安装步骤 设置 1Panel 端口（默认为22402）：8090 [1Panel Log]: 您设置的端口为：8090 设置 1Panel 面板用户（默认为5fa10eeee6）：root [1Panel Log]: 您设置的面板用户为：root 设置 1Panel 面板密码（默认为de69630bb2）： [1Panel Log]: 配置 1Panel Service cp: can't create '/etc/systemd/system': No such file or directory install.sh: line 320: systemctl: command not found install.sh: line 320: systemctl: command not found [1Panel Log]: 启动 1Panel 服务 install.sh: line 323: systemctl: command not found [1Panel Log]: 1Panel 服务启动出错!
> 
> ## 卸载也有报错
> root@iStoreOS:~# 1pctl uninstall 卸载将会完全清除 1Panel 服务和数据目录，是否继续 [y/n] : y ================== 开始卸载 1Panel Linux 服务器运维管理面板 ==================
> 
> 1. 停止 1Panel 服务进程...
>    /usr/bin/1pctl: line 54: systemctl: command not found
> 2. 删除 1Panel 服务和数据目录...
> 3. 重新加载服务配置文件...
>    /usr/bin/1pctl: line 64: systemctl: command not found
>    /usr/bin/1pctl: line 65: systemctl: command not found

请注意上方回复

**Comment by nobodysclown** [comment]
确实是之前的脚本没有删除导致的。重新安装成功了。
thanks
