### ISSUE TITLE
[FEATURE] 有计划升级更新 1panel 版本吗？

### ISSUE THREAD

**Issue by zoujingli** [gcsong023/wrt1panel#8]
### 1Panel 版本

v1.10.11-lts-wrt

### 请描述您的需求或者改进建议

有试用官方版本，功能有些完善更新，希望 wrt 版本也同步更新下。

### 请描述你建议的实现方案

有试用官方版本，功能有些完善更新，希望 wrt 版本也同步更新下。

### 附加信息

有试用官方版本，功能有些完善更新，希望 wrt 版本也同步更新下。

**Comment by gcsong023** [comment]
WRT版本没有更新1panel版本的计划。或者期待官方后续版本能够支持wrt。
